### ISSUE TITLE
headers & translatable toggles

### ISSUE THREAD

**Issue by gbdesign2023** [bogdancondorachi/kirby-table-field#1]
**A big compliment for the successful update!** 
As I use it in all my projects, the compatibility with Kirby 4 is an enrichment.

Here are my suggestions for optimizing and supplementing the functions:

- To ensure compatibility with the original v3 plug-in, it would be an advantage to deactivate/activate "thead" via toggle. Otherwise, in existing projects, the first row is defined as "thead", which already contains values, instead of row headers. It would involve a lot of extra work to adapt all tables for a large project.

- Reason: I use tables in multilingual projects in which the values (mainly numbers) are identical in all languages and editing is only possible in the main language (translate: false). Row headings are defined independently of the table and are considered for other languages. This option can, of course, be omitted for monolingual projects.

- The function to move rows and columns by drag-and-drop is a great-added value. However, the function harbors the risk that customers consciously (or unconsciously) change the order and do not consider that rows can already be sorted in the frontend using JavaScript. For example, with this: https://datatables.net/

**Comment by bogdancondorachi** [comment]
Hi, thanks for the feedback 😃 

1. I knew since the addition that it would be a problem for those who came from the initial plugin. The headers implementation is not ideal but was the simplest way (after many tries) of getting it working and keeping compatibility with the initial version. I've already planned a headers toggle for the next release.

2. I'm not so familiar with multilingual setups but I see the need for this. I'll look into adding it in the next release.

3. The latest [v2.1.0](https://github.com/bogdancondorachi/kirby-table-field/releases/tag/v2.1.0) release includes toggles for sorting and the index column as well. Check the [field properties](https://github.com/bogdancondorachi/kirby-table-field?tab=readme-ov-file#field-properties).

Please check the new version and give me some thoughts. It also supports K3 now!

**Comment by gbdesign2023** [comment]
The missing header function had forced me to use a temporary solution, but it works accurately. Basically, I am interested in optimizing projects and will adapt my template to your new plugin. After all, you don't want to carry over old ballast into new projects. 

The problem with multilingual projects is that changes are required in all languages if a table is changed, even in partial areas. If I add a line in the main language, I have to do the same in all other languages. As my tables only contain numbers, I have deactivated all additional languages of the tables with "translate: false". But the problem would be the header. This is now part of the table. Unfortunately, I don't have a solution for how to make the header editable in all languages, but lock the table fields.

**Comment by bogdancondorachi** [comment]
> **Question**: If I set "index: false", nothing changes in the .txt file. This specification is only for the output in the template, right?

It's only for the table component inside the panel. It disables the index column but you'll have to set both `index` and `sortable` to `false` in your blueprint.

By index, it refers to the table row index number. Also the sortable needs to be false as well, otherwise, you'll be left with just the column sorting witch it didn't seem right.

**Comment by gbdesign2023** [comment]
Thanks for the explanation!

In general, I'm already happy with your solution. There will always be projects where individual wishes arise. You can't take them into account. Otherwise, a small plugin becomes an oversized monster (we know that from WordPress...)

For my problem with multilingual pages, I could imagine creating 2 tables: 
the first table has only 1 line: the "thead"
the 2nd table contains the "tbody"
This way I can leave "thead" dynamic for different languages and make "tbody" editable only in the main language. I'm sure there is a more elegant solution, but I don't have the in-depth programming knowledge for that.

**Comment by bogdancondorachi** [comment]
@gbdesign2023, please check the new released [v2.2.0](https://github.com/bogdancondorachi/kirby-table-field/releases/tag/v2.2.0)

You can disable translation for non-default languages by adding `translate: false` to the field blueprint.

Unfortunately, the headers row toggle isn't coming with this release. I've been working on it but it required lots of refactoring and I'm yet to find an implementation way that does not clutter the core. I've decided to leave it for a future release as I've turned my focus on adding new features and future-proofing the codebase to the table component. But it's definitely on my priority list and would come eventually somewhere this month.

**Comment by gbdesign2023** [comment]
@bogdancondorachi **Many thanks for the successful update and the new, useful features.** 

I am pleased with the current range of functions and can use it perfectly in my projects. 
Of course, I'm also looking forward to more functions. 

Which functions I like to use with tables:
- Combine or merge cells (colspan and rowspan)
- Text alignment of individual cells

Both can also be implemented in the template output, but require a lot of effort and a strategy.
However, I assume that these functions are not possible in the panel.

By the way 1: I think the focus on Kirby 4 makes sense. 

By the way 2: It's great that your plug-in is already listed on the Kirby website.
https://getkirby.com/plugins/k4

**Comment by bogdancondorachi** [comment]
Thanks @gbdesign2023, regarding your suggestions:

- The colpan/rowspan marge is something I thought about, definitely possible but atm I'm far from that 😶‍🌫️
- The text alignment is something closer to the state current state of the plugin and would look into that on the next releases

**So far I have a short roadmap for the upcoming versions:**

1. Header row toggle
2. Clear contents option for column/row
3. Drawer content edit for column/row
4. WYSIWYG support
5. Option to hide/show column/row
5. Ability to set cell field type on column creation
6. Horizontal scroll
7. Rework draggable component to allow actions dropdown on click and sort on drag
8. Overall UI improvements

Primary focus for now would be to improve the component and content creation within the table. 😃

**Comment by bogdancondorachi** [comment]
@gbdesign2023 You can now disable the headers like this in the blueprint and then have your own headers function inside snippets.

```yaml
table:
    type: table
    headers: false
``` 
This would disable the ability to set headers inside the field (if you already have the headers set they would return as the first row).
P.S. The field blueprint has to be lowercase to work in your templates.

Now I know this won't solve your migration problem entirely but I'm afraid I can't do more than this. What I would do in your case is to manually address this at some point. You can benefit from the `headers: false` in order to remove the first row as headers, than add a new first row with your desired headers and remove the `headers: false`, this would add your first row (actual headers) as headers.

I would close this for now, if you have more discussions around this issue, please open a discussion thread [here](https://github.com/bogdancondorachi/kirby-table-field/discussions).

**Comment by gbdesign2023** [comment]
Thank you very much for your great work. The quality of your plugin is rising steeply!

I have found a small, cosmetic problem: With the setting "headers: false", the first line is still displayed as a header in the inline editor. In the dialog editor, the display is correct.

**Comment by bogdancondorachi** [comment]
@gbdesign2023 please open a new issue regarding that if you can. Also if you can demonstrate with a screenshot and more info around it. Thanks

**Comment by gbdesign2023** [comment]
@bogdancondorachi  I have now removed my temporary solution for converting the header and I am using your example in the template. Everything works perfectly now!
